### ISSUE TITLE
correction to help file for geom_shadowtext

### ISSUE THREAD

**Issue by cramjaco** [GuangchuangYu/shadowtext#1]
I think that in the geom_shadowtext.Rd file, in the example given one should call for `bg.color` rather than `bgcolor`, as the later is not recognized by shadowtext. Currently, the example leaves the background color as default.

that is, I think the author should replace

`ggplot(d, aes(x,y)) + geom_shadowtext(aes(label=label, color=label), bgcolor='firebrick')`

with

`ggplot(d, aes(x,y)) + geom_shadowtext(aes(label=label, color=label), bg.color='firebrick')`

**Comment by GuangchuangYu** [comment]
thanks
