### ISSUE TITLE
simple request of images

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [GuangchuangYu/shadowtext#10]
I am interested in this package but i have no idea if it is worth my time to install it. I was expecting an image of what this package does.
Hope you find some time to post images from your vignettes on your README file so others can quickly see if this package is something they want.

**Comment by GuangchuangYu** [comment]
see the online vignette, <https://cran.r-project.org/web/packages/shadowtext/vignettes/shadowtext.html>.
