### ISSUE TITLE
Add GeomShadowtext for referencing via geom="shadowtext" in other geoms

### ISSUE THREAD

**Issue by byteit101** [GuangchuangYu/shadowtext#11]
Currently, GeomShadowText is exported, and as such, if you, for example, wanted to annotate with this geom, you must call it  as `annotate("shadowText", label="Fun", x=1 y=1)`. This is slightly surprisingly, as I would have expected to be able to use the all-lowercase version instead.

See https://github.com/wilkelab/ggtext/commit/c4538ece186c01e06119e025bb57b6f7d2672e6e for how another project did this

**Comment by GuangchuangYu** [comment]
thanks and supported in v >= 0.1.0
