### ISSUE TITLE
background color no longer working with dev version of ggplot2

### ISSUE THREAD

**Issue by Nova-Scotia** [GuangchuangYu/shadowtext#3]
I recently installed the latest version of ggplot2:

`devtools::install_github("tidyverse/ggplot2")` and it seemed to break my code for geom_shadowtext. 

The example given in the documentation, 

```
library(ggplot2)
d <- data.frame(x = rnorm(3), y=rnorm(3), label = c('hello', 'world', '!!!'))
ggplot(d, aes(x,y)) + geom_shadowtext(aes(label=label, color=label), bgcolor='firebrick')
```

results in a black background color, not firebrick. Hopefully the issue can be ironed out!

**Comment by mschilli87** [comment]
@Nova-Scotia: For me, `colour` and `bg.colour` seem to work, while `bgcolor` doesn't.

**Comment by Nova-Scotia** [comment]
I tried with `bg.colour` & `bg.color` & `bgcolour` - none work. All black shadowtext!

**Comment by GuangchuangYu** [comment]
![image](https://user-images.githubusercontent.com/626539/68738952-9a8fee00-0622-11ea-8483-90f67a9044b1.png)
