### ISSUE TITLE
How to to increase border or margin  width?

### ISSUE THREAD

**Issue by juanpide** [GuangchuangYu/shadowtext#8]
Hello.

I'm trying to add labels to a ggplot plot (histogram) with:
geom_shadowtext(aes(label=N), vjust=-0.6, size=3, color="black", bg.colour='white') 

And it works but I would like to increase the border width or the margin around each label because some of the labels overlap the bars and are difficult to read.
I have tried with linewidth and with margin but it seems nothing changes.

How can I do it?

**Comment by GuangchuangYu** [comment]
please use the `bg.r` argument.
